### ISSUE TITLE
投稿時にタイムライン・ヒストリーの最上部に追記

### ISSUE THREAD

**Issue by Yudai-Saito** [Yudai-Saito/Homete#235]
- [x] 投稿されたときにタイムラインかヒストリーの上に投稿が追記されるようにする
- [x] 投稿完了時に顔と名前がレスポンスされるから受け取る

**Comment by shiratoriren** [comment]
post_idも一緒にレスポンスしてくれればそれだけで先頭に追記されるかと思います

**Comment by Yudai-Saito** [comment]
投稿で全体更新かけて、現在見てる位置に留まらせるようにする

**Comment by Yudai-Saito** [comment]
最新投稿追記更新の差分で、どちらにしろずれるから対策は必要になる

**Comment by shiratoriren** [comment]
投稿を追記してもずれないようにする処理が書けたんで、あとは追記だけになりました
