### ISSUE TITLE
確定していない文章を設定する

### ISSUE THREAD

**Issue by Yudai-Saito** [Yudai-Saito/Homete#344]
- [x] LP
- [x] ログインオーバーレイ
- [x] 未ログインオーバーレイ
- [x] 404
- [x] LPボタンのカラー変更
- [x] LPナビゲーション削除

**Comment by Yudai-Saito** [comment]
# ログイン

HOMETEは誰かに褒めてもらえるやさしいSNSだよ
日常のどんなことでも投稿しちゃおう！


利用規約、プライバシーポリシーに同意したうえでログインしてください（利用規約とプライバシーポリシーはリンク張る）

**Comment by shiratoriren** [comment]
# 404NotFound
ページが見つかりませんでした
猫画像
Topへ戻る

**Comment by Yudai-Saito** [comment]
キャッチコピー
なぜ生まれたか

こんなものあったらいいな
治安がいいSNS欲しい
匿名で投稿したい
とか

いつ使えるのか

使い方
投稿を3個くらい並べて投稿を連想できるように

匿名性

最後
