### ISSUE TITLE
WSが複数接続されていて投稿が複数合流されてしまう

### ISSUE THREAD

**Issue by Yudai-Saito** [Yudai-Saito/Homete#380]

**Comment by shiratoriren** [comment]
ログアウト直後の未ログイン状態のタイムラインでのみ、updatePostsに入る投稿が二重になる

**Comment by shiratoriren** [comment]
ログアウト時にwebSocketの接続が残ったままであるため、そのままトップに行くと新しく接続をして、二重に新規投稿を通知してくる。
→ログアウト時にwebSocketの接続を切る。

トップでリロードをかけた際もログには接続が残った状態であるため、明示的に接続を切る必要がある。

**Comment by Yudai-Saito** [comment]
トップで複数回リロードかけてもコネクションは切断されていた。
リロードに対する切断処理はしなくて良い。

**Comment by Yudai-Saito** [comment]
/topへ戻ると直前の投稿情報も消えてしまっている
これで自分のを受信する場合がある
解決策は、自分のidが来たら消すのが一番ベストな気もする
