### ISSUE TITLE
画面拡大を禁止する

### ISSUE THREAD

**Issue by Yudai-Saito** [Yudai-Saito/Homete#405]
- リアクションを押していると画面拡大してしまうので禁止したい
- [ ] 全ての画面で拡大を禁止する

**Comment by shiratoriren** [comment]
現状、javascriptでできる画面拡大操作の禁止は
ピンチイン/ピンチアウトは何故か一部を起点に操作すると拡大縮小できてしまう
ダブルタップは、１回目のタップからある程度の閾値を設けて２回目がそれ以内ならタップイベントを起こさないというものであるため、サービス全体のレスポンスに影響が出る
以上からこのイシューは達成不可能
