### ISSUE TITLE
新規登録とパスワードリセットのメール送信完了のメッセージの統一

### ISSUE THREAD

**Issue by Yudai-Saito** [Yudai-Saito/Homete#53]
新規登録もパスワードリセットもメールアドレスが存在する、しないを表示するのはセキュリティ的によろしくないため、どちらも送信ボタンを押したら送信しました。と表示するように変更する。

**Comment by shiratoriren** [comment]
@shiratoriren components内のRequestmailでレスポンスコードをチェックしないことにしたから Signup_requmail内でチェックして分岐するように変更すること

**Comment by shiratoriren** [comment]
@shiratoriren components内のRequestmailでの書き方だとsignupにしか対応できていない
