### ISSUE TITLE
未ログインユーザに対するトップ画面の構成変更処理

### ISSUE THREAD

**Issue by Yudai-Saito** [Yudai-Saito/Homete#88]
・TOP画面での未ログインユーザの判定
・未ログインユーザ用メニューテンプレート作成

再リロード -> TOP
 :有効期限が乗っているcookieを保持
　　:リロードかかったら有効期限確認
　　　:期限外の場合は未ログインユーザ

再リロードせず24時間経過 -> tokenが必要なAPI
 :res.code 401が飛んできたら未ログインユーザ
　:認証が必要なapi叩いてる部分で全てエラーコードの処理する

**Comment by Yudai-Saito** [comment]
1. tokenがcookieにある場合は、有効か確認用APIを叩いて友好確認

**Comment by shiratoriren** [comment]
<img width="409" alt="スクリーンショット 2022-01-06 16 32 52" src="https://user-images.githubusercontent.com/60804269/148364406-1544ea94-916a-4897-b957-f5496dd9d580.png">
<img width="423" alt="スクリーンショット 2022-01-06 16 44 16" src="https://user-images.githubusercontent.com/60804269/148364414-ce0746b6-c4f1-42be-bbec-85396dd9e8dd.png">
<img width="537" alt="スクリーンショット 2022-01-06 16 44 24" src="https://user-images.githubusercontent.com/60804269/148364417-a53ff4c0-9300-4906-9ebb-8aa5d1c37e8e.png">
